### ISSUE TITLE
云吧消息推送在浏览器客户端收不到推送信息

### ISSUE THREAD

**Issue by jing1037250894** [yunba/yunba-issues#1]
>请按下方提示如实填写您的问题、需求或建议（在合适的选项后填写[ Y ]，不涉及的内容可忽略），并在右侧选择合适的标签(Label)。

## 基本信息

* **云巴用户名**：chenqi
* **云巴应用名**：sso-client
* 使用场景：App[  ]  Web[ Y ]  物联网[  ]
* 服务端 SDK：yunba-socket.io-java-sdk-master
* 服务端 SDK 版本号：当前最新版[  ]  其他版本：
* 客户端 SDK 1：yunba-javascript-sdk-master
* 客户端 SDK 1 版本号：当前最新版[  ]  其他版本：
* 客户端 SDK 2：
* 客户端 SDK 2 版本号：当前最新版[  ]  其他版本：
* 网络类型：
* 日活：

## 问题

* 描述：
* 网络状况：
* 问题严重程度：一般[  ]  中等[  ]  严重[ Y ]
* 能否重现：能[ Y ]  否[  ]
* 重现步骤：
* 消息发布方式：Topic[  ]  Alias[ Y ]
* 涉及的 API：
* 抓包日志： 获取请求流没有任何关于云吧获取推送消息的记录
* 备注：

## 需求

* 描述：我需要在浏览器端做账号登陆踢出功能，当账号重复登录时，踢出先前登陆的所有账号
* 备注：

## 建议

* 描述：之前正常的情况下，能够打开浏览器F12开发者工具时，在请求流里边可以看到有云吧的请求信息，但是在获取不到推送的情况下，看请求流记录没有任何记录。但是在云吧管理后台是有推送消息的记录的
* 备注：

**Comment by LirisFlow** [comment]
@jing1037250894 
- 与云巴的连接是否正常，客户端能否收到 Topic 的消息？
- 该客户端的  alias 是否正确？可以通过 [get_alias](https://yunba.io/docs/js_sdk_api_manual#get_alias) 查看一下。注意，如果设置了相同的 alias，会覆盖之前的 alias。

**Comment by jing1037250894** [comment]
用官网的demo把appKey改成我的那个key，然后Get Alias，返回接口是空的，是一个账号只能设置一个别名吗，只有最新的别名才会获取到推送消息吗，我项目里边只有一个账号，但是要用于做用户账号登陆互踢功能，要怎么做呢

**Comment by LirisFlow** [comment]
返回空应该是未设置别名，或者是被同一个 [Appkey](https://yunba.io/docs/product_kb_app_key) 下的其他客户端设置了同样的别名。一个 Appkey 下，别名是唯一的。一个客户端也是只有一个别名，设置新的别名后，旧的别名就无效了。你先看一下 [别名的介绍文档](https://yunba.io/docs/product_kb_topic_and_alias#别名alias)。 @jing1037250894

**Comment by jing1037250894** [comment]
我感刚刚十二楼，一个客户端对别名只能设置一个，多个客户端一个appKey可以设置多个别名是可以的，然后在服务端分别向每个客户端的别名推送消息，是可以收到的。那我之前的那个就是收不到消息的问题了呢。

**Comment by lichunjing** [comment]
OK

**Comment by LirisFlow** [comment]
@jing1037250894 你的问题解决了吗？

**Comment by jing1037250894** [comment]
弄明白了，但是希望延迟的问题不要出现
